function [] = AnimSimControl(t_sim, X_out, vec_ref, scenario_id, pert_id)
% ANIMSIMCONTROL - Animates and records the 3D visual workspace motion of the 
% daVinci surgical arm.
%
% Saves an animated .gif asset directly into 'Figures/Tracking'.

a2_val = 0.4;
x_ref  = vec_ref(1,:);
y_ref  = vec_ref(2,:);
z_ref  = vec_ref(3,:);

% Define and verify destination folder structure
folder_path = fullfile('Figures', 'Tracking');
if ~exist(folder_path, 'dir')
    mkdir(folder_path);
end

% Generate dynamic context-aware filename string for the GIF file
gif_name = sprintf('Animation_Scenario_%s_%s.gif', char(scenario_id), char(pert_id));
gif_full_path = fullfile(folder_path, gif_name);

fps = 30;
delay_time = 1 / fps; % Time window per frame in seconds
duration = t_sim(end); 
t_anim = linspace(0, duration, round(duration * fps));

% Uniform data interpolation matching standard time steps
q1_anim = interp1(t_sim, X_out(:,1), t_anim, 'linear', 'extrap');
q2_anim = interp1(t_sim, X_out(:,2), t_anim, 'linear', 'extrap');
q3_anim = interp1(t_sim, X_out(:,3), t_anim, 'linear', 'extrap');

% Pre-calculate the ongoing Cartesian trace path generated by the tip
trace_x = zeros(size(t_anim)); trace_y = zeros(size(t_anim)); trace_z = zeros(size(t_anim));
for i = 1:length(t_anim)
    r_i = a2_val * cos(q2_anim(i)) + q3_anim(i) * sin(q2_anim(i));
    trace_x(i) = cos(q1_anim(i)) * r_i;
    trace_y(i) = sin(q1_anim(i)) * r_i;
    trace_z(i) = a2_val * sin(q2_anim(i)) - q3_anim(i) * cos(q2_anim(i));
end

% Canvas anchoring trackers for layout size freezing
target_h = 0;
target_w = 0;

disp(['=> Rendering and compiling frames into GIF: ' gif_full_path]);
for i = 1:length(t_anim)
    q_current = [q1_anim(i); q2_anim(i); q3_anim(i)];
    
    % Draw the robotic arm layout structure
    PlotRobot_dV(q_current, a2_val);
    hold on;
    
    % Overlay the clinical task reference track path
    plot3(x_ref, y_ref, z_ref, 'Color', [0.7 0.7 0.7], 'LineWidth', 1.5, 'DisplayName', 'Task Reference');
    
    % Highlight path percurrent history up to the current frame index
    plot3(trace_x(1:i), trace_y(1:i), trace_z(1:i), 'm-', 'LineWidth', 2, 'DisplayName', 'Executed Path');
    
    % Smart camera view orientation selection based on plane movement profiles
    if max(abs(trace_y)) < 0.01 && max(abs(q1_anim)) < 0.01 
        view(100, 10); % Optimization profile for YZ-planar tracking behaviors
    else
        view(135, 25); % Optimization profile for spatial 3D helical tracking shapes
    end
    
    title(sprintf('Assumed Model | Scenario %s (%s) | Time: %.2f s', scenario_id, pert_id, t_anim(i)));
    grid on; axis equal;
    
    drawnow;
    
    % Grab current active graphic frame buffer
    current_frame = getframe(gcf);
    
    % Canvas layout dimension guard to shield imwrite from character-width pixel jitter
    if i == 1
        target_h = size(current_frame.cdata, 1);
        target_w = size(current_frame.cdata, 2);
    else
        if size(current_frame.cdata, 1) ~= target_h || size(current_frame.cdata, 2) ~= target_w
            current_frame.cdata = imresize(current_frame.cdata, [target_h, target_w]);
        end
    end
    
    % Convert frame RGB matrix to indexed image for GIF specification compatibility
    im = frame2im(current_frame);
    [imind, cm] = rgb2ind(im, 256);
    
    % Write/Append current frame to the GIF file asset
    if i == 1
        % 'Loopcount', inf guarantees the GIF loops continuously forever
        imwrite(imind, cm, gif_full_path, 'gif', 'Loopcount', inf, 'DelayTime', delay_time);
    else
        imwrite(imind, cm, gif_full_path, 'gif', 'WriteMode', 'append', 'DelayTime', delay_time);
    end
    
    hold off;
end
disp('=> GIF tracking asset successfully exported!');
end