function B_numeric_expression = GetBmatrix(in1)
%GetBmatrix
%    B_numeric_expression = GetBmatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    11-Jun-2026 00:30:41

q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q2);
t3 = sin(q2);
t4 = q2.*2.0;
t5 = q3.^2;
t8 = q3.*9.966e-1;
t6 = t2.^2;
t7 = sin(t4);
t9 = -t8;
t10 = t5.*1.661;
t11 = t2.*9.293999999510141e-9;
t12 = t3.*1.2e-2;
t13 = -t12;
t14 = t11+t13;
B_numeric_expression = reshape([t6.*2.609925e-1-t7.*2.2423496965e-1+t9+t10+q3.*t7.*7.4745e-1-t5.*t6.*1.661+t6.*t8+2.0849e-1,t14,0.0,t14,t9+t10+7.699725e-1,-7.4745e-1,0.0,-7.4745e-1,1.661],[3,3]);
end
