function B_numeric_expression = GetBmatrix(in1)
%GetBmatrix
%    B_numeric_expression = GetBmatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    28-May-2026 22:09:04

q2 = in1(2,:);
q3 = in1(3,:);
t2 = q2.*2.0;
t3 = q3.^2;
t4 = cos(t2);
t5 = sin(t2);
mt1 = [q3.*(-3.3e+1./2.5e+2)+t3.*(3.3e+1./5.0e+1)+t4.*3.285702291666667e-1-t5.*(3.3e+1./6.25e+2)+q3.*t4.*(3.3e+1./2.5e+2)+q3.*t5.*(6.6e+1./1.25e+2)-t3.*t4.*(3.3e+1./5.0e+1)+3.585328541666667e-1,0.0,0.0,0.0];
mt2 = [q3.*(-3.3e+1./1.25e+2)+t3.*(3.3e+1./2.5e+1)+6.951262083333333e-1,-6.6e+1./1.25e+2,0.0,-6.6e+1./1.25e+2,3.3e+1./2.5e+1];
B_numeric_expression = reshape([mt1,mt2],3,3);
end
