function IK_subs = GetIKnumeric(Pe_x,Pe_y,Pe_z)
%GetIKnumeric
%    IK_subs = GetIKnumeric(Pe_x,Pe_y,Pe_z)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    01-Dec-2025 19:13:58

t2 = Pe_x.^2;
t3 = Pe_y.^2;
t4 = Pe_z.^2;
t5 = Pe_y.*1i;
t6 = Pe_z.*1i;
t7 = Pe_x+t5;
t8 = t2+t3;
t9 = angle(t7);
t10 = sqrt(t8);
t11 = t4+t8-4.0./2.5e+1;
t12 = t6+t10;
t14 = sqrt(t11);
t13 = angle(t12);
t15 = t14.*1i;
t16 = t15+2.0./5.0;
t17 = angle(t16);
IK_subs = reshape([t9,t9,t13+t17,t13-t17,t14,-t14],[2,3]);
end
