function n_numeric_expression = Getnvector(in1,w)
%Getnvector
%    N_NUMERIC_EXPRESSION = Getnvector(IN1,W)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    11-Jun-2026 00:30:41

dq1 = in1(4,:);
dq2 = in1(5,:);
dq3 = in1(6,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q2);
t3 = sin(q2);
t4 = dq1.^2;
t5 = dq2.^2;
t6 = q2.*2.0;
t7 = q3.^2;
t11 = q3.*1.661;
t8 = cos(t6);
t9 = t2.^2;
t10 = sin(t6);
et1 = dq1.*2.0-dq1.*dq3.*4.983e-1-t2.*t5.*1.2e-2-t3.*t5.*9.293999999510141e-9;
et2 = dq1.*dq2.*t8.*(-4.484699393e-1)+dq1.*dq3.*t8.*4.983e-1-dq1.*dq2.*t10.*2.609925e-1+dq1.*dq3.*t10.*7.4745e-1+dq1.*dq3.*t11+dq1.*dq2.*q3.*t8.*1.4949-dq1.*dq3.*q3.*t8.*1.661-dq1.*dq2.*q3.*t10.*9.966e-1+dq1.*dq2.*t7.*t10.*1.661;
et3 = dq2.*2.0+t2.*1.21521375e+1-t3.*4.888323-dq2.*dq3.*9.966e-1+q3.*t3.*1.629441e+1+t4.*t8.*2.2423496965e-1+t4.*t10.*1.3049625e-1+dq2.*dq3.*q3.*3.322-q3.*t4.*t8.*7.4745e-1;
et4 = q3.*t4.*t10.*4.983e-1-t4.*t7.*t10.*8.305e-1;
n_numeric_expression = [et1+et2;et3+et4;dq3.*5.0+q3.*5.0e+2-t2.*1.629441e+1-w.*5.0e+2-t4.*(t9.*4.983e-1+t10.*3.73725e-1+t11-q3.*t9.*1.661-4.983e-1)-t5.*(t11-4.983e-1)-1.8e+2];
end
