function n_numeric_expression = Getnvector(in1)
%Getnvector
%    N_NUMERIC_EXPRESSION = Getnvector(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    28-May-2026 22:09:04

dq1 = in1(4,:);
dq2 = in1(5,:);
dq3 = in1(6,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q2);
t3 = sin(q2);
t4 = dq1.^2;
t5 = q2.*2.0;
t6 = q3.^2;
t9 = q3.*(3.3e+1./5.0e+1);
t7 = cos(t5);
t8 = sin(t5);
t11 = t7.*(3.3e+1./5.0e+2);
t12 = t8.*(3.3e+1./1.25e+2);
t13 = q3.*t7.*(-3.3e+1./5.0e+1);
t14 = q3.*t8.*(3.3e+1./2.5e+2);
t15 = t7.*(3.3e+1./6.25e+2);
t16 = q3.*t7.*(6.6e+1./1.25e+2);
t17 = t6.*t8.*(3.3e+1./5.0e+1);
t21 = t8.*3.285702291666667e-1;
t18 = -t16;
t19 = -t17;
t20 = t9+t11+t12+t13-3.3e+1./5.0e+2;
t22 = t14+t15+t18+t19+t21;
n_numeric_expression = [dq1.*2.0+dq1.*dq3.*t20.*2.0-dq1.*dq2.*t22.*2.0;dq2.*2.0+t2.*2.212155e+1-t3.*1.29492+q3.*t3.*1.29492e+1+t4.*t22+dq2.*dq3.*(q3-1.0./1.0e+1).*(6.6e+1./2.5e+1);dq3.*5.0+q3.*5.0e+2-t2.*1.29492e+1-t4.*t20-dq2.^2.*(q3.*(3.3e+1./2.5e+1)-3.3e+1./2.5e+2)-1.0e+2];
end
